jobs:
  stale:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/stale@v9
      with:
        days-before-close: -1
        days-before-issue-stale: -1
        days-before-pr-stale: 30
        stale-pr-message: ''
name: Mark inactive PRs as stale
on:
  repository_dispatch:
    types: trigger-ga___pr-stale.yml
