env:
  LC_ALL: en_US.UTF-8
jobs:
  publish-site:
    if: github.repository == 'line/armeria'
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Install svgbob_cli
      run: 'sudo apt-get -y install cargo && cargo install svgbob_cli

        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

        '
    - continue-on-error: true
      id: setup-jdk-21
      name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '21'
    - continue-on-error: true
      name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
    - continue-on-error: true
      name: Build the site
      run: './gradlew --no-daemon --stacktrace  --max-workers=2 --parallel -PgithubToken=${{
        secrets.GITHUB_TOKEN }} site

        '
    - continue-on-error: true
      name: Deploy the site
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: site/public
name: Publish Armeria site
on:
  repository_dispatch:
    types: trigger-ga___publish-site.yml
