env:
  LC_ALL: en_US.UTF-8
jobs:
  update-psl:
    if: github.repository == 'line/armeria'
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      id: setup-jdk-21
      name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '21'
    - continue-on-error: true
      name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
    - continue-on-error: true
      name: Update public suffix list
      run: './gradlew --no-daemon --stacktrace :core:publicSuffixes

        '
    - continue-on-error: true
      id: import_gpg
      name: Import GPG key
      uses: crazy-max/ghaction-import-gpg@v6
      with:
        git_commit_gpgsign: true
        git_user_signingkey: true
        gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
        passphrase: ${{ secrets.GPG_PASSWORD }}
    - continue-on-error: true
      name: Create pull request
      uses: peter-evans/create-pull-request@v6
      with:
        add-paths: 'core/src/main/resources/com/linecorp/armeria/public_suffixes.txt

          '
        author: Meri Kim <dl_armeria@linecorp.com>
        branch: update-public-suffixes
        commit-message: Update public suffix list
        committer: Meri Kim <dl_armeria@linecorp.com>
        delete-branch: true
        label: miscellaneous
        title: Update public suffix list
name: Update Public Suffix List
on:
  repository_dispatch:
    types: trigger-ga___public-suffixes.yml
